### ISSUE TITLE
Create Zenodo repository for the tutorial

### ISSUE THREAD

**Issue by santisoler** [simpeg/agrogeo24#19]
Would be nice to have the repo for the tutorial uploaded to Zenodo, so we can cite it through a DOI.

## TODO

- [ ] Draft a new Zenodo repo (don't publish it)
- [ ] Book a DOI
- [ ] Include the DOI in the `README.md`. We could also include a `## Citing` section with instructions on how to cite.
- [ ] Create a release
- [ ] Download zip from the release
- [ ] Upload zip to Zenodo
- [ ] Publish the Zenodo repo

**Comment by rowanc1** [comment]
Also, note that the conference will provide a DOI for this that directly resolves to the conference website, this will be hosted by crossref and include additional metadata (for citations etc).
